ip1:
  hostname: dmzdp3
  username: admin
  password: pass
  port: 5554
  proxies:
    https: http://localhost:3128
ip2:
  hostname: dmzdp4
  username: admin
  password: pass
  port: 5554
  proxies:
    https: http://localhost:3128
ip3:
  hostname: dmzdp3
  username: admin
  password: pass
  port: 5554
  proxies:
    https: http://localhost:3128
