ip1:
  hostname: host1
  username: admin
  password: pass
  port: 5554
  proxies:
    https: http://localhost:3128
ip2:
  hostname: host2
  username: admin
  password: pass
  port: 5554
  proxies:
    https: http://localhost:3128
ip3:
  hostname: host3
  username: admin
  password: pass
  port: 5554
  proxies:
    https: http://localhost:3128
